### ISSUE TITLE
plot_marker_profiles issues

### ISSUE THREAD

**Issue by JosieAC** [TomSmithCGAT/pRolocExt#1] opened 2021-11-16 14:06 UTC
https://github.com/TomSmithCGAT/pRolocExt/blob/09ba2991f2e2330e074040a5ecf8c4ec383ba3fc/R/linear_profiles.R#L96-L100

There are a couple issues with `plot_marker_profiles`:

1) The following error occurs when running the code as is with my version of R:
` Error: Only strings can be converted to symbols`
This was resolved by changing all `!!sym(fcol/group_by)` to `!!sym(as.String(fcol/group_by))`. 

2) However, when doing so a further error occurred when using `group_by = NULL` :
```
Error in sym(as.String(group_by)) : 
attempt to use zero-length variable name
```
The function worked when applying the changes in issue 1 and putting a pData parameter (e.g. replicate) for issue 2. I assume this happens as this is turning "NULL" into a string?  Not sure if this is to do with my different version of R or packages?

**Comment by TomSmithCGAT** [comment] 2021-11-16 15:02
Yep, you're right that it's the NULL that's the issue.

The problem is that the function defaults to `group_by=NULL` but checks if the user has supplied *any* value for this argument, even if it's NULL https://github.com/TomSmithCGAT/pRolocExt/blob/09ba2991f2e2330e074040a5ecf8c4ec383ba3fc/R/linear_profiles.R#L159.

If you drop `group_by=NULL` from your function call, it should work fine. In the meantime, I'll update to avoid the error.

**Comment by TomSmithCGAT** [comment] 2021-11-16 15:23
Resolved in https://github.com/TomSmithCGAT/pRolocExt/commit/d898aff6b6a6fd85fe1196e79f078832bbdb9d82 hopefully..

**Closed as completed by TomSmithCGAT** 2021-11-16 15:23 UTC
Labels: bug
